services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nature-db
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Abc12345!
      - MSSQL_PID=Developer
    volumes:
      - sql_server_data:/var/opt/mssql

volumes:
  sql_server_data:
