services:
  api:
    build:
      context: .
      dockerfile: NatureAPI/Dockerfile
    container_name: nature-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=NatureDB;User=sa;Password=Abc12345!
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nature-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Abc12345!
      - MSSQL_PID=Developer
    volumes:
      - sql_server_data:/var/opt/mssql

volumes:
  sql_server_data:
